blank_issues_enabled: false

contact_links:
  - name: 🌸 p5.js Issues
    url: https://github.com/processing/p5.js/issues
    about: Report issues with the p5.js here.
  - name: 🖥️ Web Editor Issues
    url: https://github.com/processing/p5.js-web-editor/issues
    about: Report issues with the p5.js web editor here.
  - name: 💬 Forum
    url: https://discourse.processing.org/c/p5js
    about: Have other questions about using p5.js? Ask them here!